### ISSUE TITLE
add type annotations to every funtion

### ISSUE THREAD

**Issue by michelkluger** [michelkluger/excel2image#5]
the reason to do this is to have more clarity for future development,

- [x] every input param should be annotated 
- [x] every output as well 

acceptance criteria:

- [x] mypy should pass using python 3.12
- [x] add mypy to CI

**Comment by michelkluger** [comment]
study mypy and understand what is mypy
understand typing annotation in python


https://www.youtube.com/watch?v=bO3-CWDMxCk
https://www.youtube.com/watch?v=QORvB-_mbZ0&t=560s

**Comment by michelkluger** [comment]
understand typing annotation in python

**Comment by BarbaraLearn** [comment]
I guess that could be considered done?
